require: rubocop-rails

AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "app/channels/**/*"
    - "app/views/**/*"
    - "lib/**/*"
    - "log/**/*"
    - "script/**/*"
    - "policy/*"
    - "tmp/**/*"
    - "bin/*"
    - "config.ru"
    - "Rakefile"
    - spec/rails_helper.rb
    - "vender/**/*"

Style/Documentation:
  Enabled: false
StringLiterals:
  EnforcedStyle: double_quotes
Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 20
